name: eurecom
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: OpenAirInterface Remote Radio Unit
description: |
  OpenAirInterface remote radio unit (RRU) implementing functional split NGFI
  IF5 and IF4.5 that connects to the OpenAirInterface LTE eNB. Connect
  commercial UEs with the band of your choice.
grade: devel
confinement: devmode

apps:
  oai-rru:
    command: rru/bin/snap_environment.sh ./rru/bin/rru

parts:
  rru:
    plugin: nil
    source: https://gitlab.eurecom.fr/oai/openairinterface5g.git
    source-branch: rru-txwrite-modification
    build: |
      cd cmake_targets
      ./build_oai -I -w USRP --install-optional-packages \
          --uhd-images-dir ../common/uhd_images
      ./build_oai --eNB -w USRP -t ETHERNET -c -C
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/rru
      cp -r targets/bin $SNAPCRAFT_PART_INSTALL/rru/
      cp -r common/uhd_images $SNAPCRAFT_PART_INSTALL/
      cp cmake_targets/snap_environment.sh $SNAPCRAFT_PART_INSTALL/rru/bin/
    stage:
      - rru/bin/*
      - usr/lib/*
      - lib/*
      - uhd_images/*
    organize:
      rru/bin/liboai_eth_transpro.so.Rel10: usr/lib/liboai_transpro.so
      rru/bin/liboai_usrpdevif.so.Rel10: usr/lib/liboai_device.so
      rru/bin/lte-softmodem.Rel10: rru/bin/rru
